version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: toadAspDB
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  web:
    container_name: toadAspWeb
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: